language: php

php:
    - 5.6
    - 7.0
    - 7.1

env:
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.3.*

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update --prefer-source

script: phpunit
