language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    - SYMFONY_VERSION=4.4.*

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update --prefer-source

script:
    - make analysis
    - make unit
